image: python:3.6

stages: 
    - test
    - deploy 

before_script: 
    - apt update -qq && apt install libmysqlclient-dev
    - pip install -r requirements.txt

test: 
    stage: test
    only: 
        - ci_test
    script: 
        - az login --msi
        - az webapp deployment source sync -n prodigal-gamma -g prodigal
        - python prodigal_app/tests.py

deploy: 
    stage: deploy
    only: 
        - ci_test
    script: 
        - pip install azure-cli 
        - az login --msi
        - az webapp deployment source sync -n Prodigal-beta -g Prodigal-beta
        - az logout
        - echo "[INFO] Currently testing out with docker deploy."
