Selenium_Test:
  script:
    - az login --msi
    - az webapp deployment source sync -n prodigal-gamma -g prodigal
    - coverage run manage.py test prodigal_app && coverage html && coverage report
  stage: test
  only:
    - master

Azure_Deploy:
  script:
    - az webapp deployment source sync -n Prodigal-beta -g Prodigal-beta
    - az logout
  stage: deploy
  only:
    - master