Selenium_Test:
  script:
    - pip3 install -r requirements.txt
    - az login --msi
    - az webapp deployment source sync -n prodigal-gamma -g prodigal
    - cd /home/gitlab-runner/builds/b74f8bb5/0/prodigal/pro-frontend/
    - coverage run manage.py test prodigal_app/
    - coverage report

  stage: test
  only:
    - master

Azure_Deploy:
  script:
    - az webapp deployment source sync -n Prodigal-beta -g Prodigal-beta
    - az logout
  stage: deploy
  only:
    - master