image: python:3.6

stages: 
    - test
    - deploy 

before_script: 
    - export PATH=$PATH:/builds/prodigal/pro-frontend/
    - apt update -qq && apt install -y libmysqlclient-dev
    - pip install -r requirements.txt

test: 
    stage: test
    only: 
        - ci_test
    script: 
        - python manage.py test

deploy: 
    stage: deploy
    only: 
        - ci_test
    script: 
        - echo "[INFO] Currently testing out with docker deploy."
