image: python:3.6

stages: 
    - test
    - deploy 

before_script: 
    - find ~/ -iname "chromedriver"
    - export PATH=$PATH:$(find ~/ -iname "chromedriver")
    - echo $PATH
    - apt update -qq && apt install -y libmysqlclient-dev
    - pip install -r requirements.txt
    - export PATH=$PATH:$(find ~/ -iname "chromedriver")

test: 
    stage: test
    only: 
        - ci_test
    script: 
        - python manage.py test

deploy: 
    stage: deploy
    only: 
        - ci_test
    script: 
        - echo "[INFO] Currently testing out with docker deploy."
