Selenium_Test:
  script:
    - az login --msi
    - az webapp deployment source sync -n prodigal-gamma -g prodigal
    -python3 /home/gitlab-runner/builds/b74f8bb5/0/prodigal/pro-frontend/prodigal_app/tests_backend.py
  stage: test
  only:
    - master

Azure_Deploy:
  script:
    - az webapp deployment source sync -n Prodigal-beta -g Prodigal-beta
    - az logout
  stage: deploy
  only:
    - master