# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_delete_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, db_column='userId', null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'demo_chat',
                'managed': False,
            },
        ),
    ]
